use std::path::{Path, PathBuf};

/// Settings that describe one computer: where the course material lives, where the automation
/// scripts are, and where the external tools were installed. They were literals in `config.rs`,
/// which meant the source could not be shared and nobody else could build it against their own
/// folders. They are now read from a JSON file and emitted as the same compile-time constants,
/// so every call site is unchanged and the values never enter version control.
///
/// `guide-watcher.local.json` is yours and is git-ignored. `guide-watcher.example.json` is the
/// template that ships, and is used when no local file exists so a fresh clone still builds.
const LOCAL: &str = "guide-watcher.local.json";
const EXAMPLE: &str = "guide-watcher.example.json";

/// Every setting the generated module must define, with the type it is emitted as.
const STRINGS: &[&str] = &[
    "watch_dir",
    "fourth_semester_root",
    "fifth_semester_root",
    "template_file",
    "depth_contract_file",
    "render_slides_script",
    "guide_lint_script",
    "guide_lint_requirements",
    "supplementary_collect_script",
    "lms_agent_root",
    "lms_node_executable",
    "lms_tsx_cli",
    "ffmpeg_executable",
    "ffprobe_executable",
    "transcription_uv_executable",
    "transcription_script",
    "circuit_lab_course_id",
];

fn main() {
    tauri_build::build();

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let root = manifest.parent().unwrap_or(&manifest).to_path_buf();
    let local = root.join(LOCAL);
    let example = root.join(EXAMPLE);
    println!("cargo:rerun-if-changed={}", local.display());
    println!("cargo:rerun-if-changed={}", example.display());

    let source = if local.is_file() { &local } else { &example };
    if !source.is_file() {
        panic!(
            "no machine settings found. Copy {} to {} and edit it for this computer.",
            example.display(),
            local.display()
        );
    }
    let text = std::fs::read_to_string(source)
        .unwrap_or_else(|error| panic!("could not read {}: {error}", source.display()));
    let settings = parse(&text, source);

    let mut generated = String::from(
        "// Generated by build.rs from the machine settings JSON. Do not edit.\n",
    );
    for key in STRINGS {
        let value = settings.get(key).unwrap_or_else(|| {
            panic!(
                "{} is missing the setting \"{}\"; copy it from {}",
                source.display(),
                key,
                example.display()
            )
        });
        generated.push_str(&format!(
            "pub const {}: &str = {};\n",
            key.to_uppercase(),
            quote(value)
        ));
    }

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("machine_settings.rs");
    std::fs::write(&out, generated)
        .unwrap_or_else(|error| panic!("could not write {}: {error}", out.display()));
}

/// A deliberately small reader for a flat `{"key": "value"}` object, so the build needs no JSON
/// dependency. Comments (`//`) are allowed so the example file can explain itself.
fn parse(text: &str, source: &Path) -> Vec<(String, String)> {
    let mut settings = Vec::new();
    for (number, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("//") || line == "{" || line == "}" {
            continue;
        }
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let key = key.trim().trim_matches('"').to_string();
        let value = value.trim().trim_end_matches(',').trim();
        if !value.starts_with('"') || !value.ends_with('"') || value.len() < 2 {
            panic!(
                "{}:{}: every setting must be a quoted string",
                source.display(),
                number + 1
            );
        }
        settings.push((key, unescape(&value[1..value.len() - 1])));
    }
    settings
}

trait Lookup {
    fn get(&self, key: &str) -> Option<&str>;
}

impl Lookup for Vec<(String, String)> {
    fn get(&self, key: &str) -> Option<&str> {
        self.iter()
            .find(|(name, _)| name == key)
            .map(|(_, value)| value.as_str())
    }
}

/// JSON escapes that appear in Windows paths.
fn unescape(value: &str) -> String {
    value.replace("\\\\", "\\").replace("\\/", "/")
}

/// Emit a Rust string literal that cannot be broken by a backslash or a quote in a path.
fn quote(value: &str) -> String {
    let mut literal = String::from("\"");
    for character in value.chars() {
        match character {
            '"' => literal.push_str("\\\""),
            '\\' => literal.push_str("\\\\"),
            _ => literal.push(character),
        }
    }
    literal.push('"');
    literal
}
