use std::path::{Path, PathBuf};

/// Everything that describes one person's setup: where their material lives, where the automation
/// scripts are, which external tools they installed, and what their subjects are called. These
/// were literals in the source, which meant the app only worked for its author. They are read
/// from JSON here and emitted as the same compile-time constants, so every call site is unchanged
/// and nobody's folder layout enters version control.
///
/// `guide-watcher.local.json` is yours and is git-ignored. `guide-watcher.example.json` ships as
/// the template and is used when no local file exists, so a fresh clone still builds.
const LOCAL: &str = "guide-watcher.local.json";
const EXAMPLE: &str = "guide-watcher.example.json";

/// Path-like settings, emitted as `pub const NAME: &str`.
const STRINGS: &[&str] = &[
    "watch_dir",
    "fourth_semester_root",
    "fifth_semester_root",
    "template_file",
    "depth_contract_file",
    "render_slides_script",
    "guide_lint_script",
    "guide_lint_requirements",
    "supplementary_collect_script",
    "lms_agent_root",
    "lms_node_executable",
    "lms_tsx_cli",
    "ffmpeg_executable",
    "ffprobe_executable",
    "transcription_uv_executable",
    "transcription_script",
    "circuit_lab_course_id",
];

fn main() {
    tauri_build::build();

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let root = manifest.parent().unwrap_or(&manifest).to_path_buf();
    let local = root.join(LOCAL);
    let example = root.join(EXAMPLE);
    println!("cargo:rerun-if-changed={}", local.display());
    println!("cargo:rerun-if-changed={}", example.display());

    let source = if local.is_file() { &local } else { &example };
    let text = std::fs::read_to_string(source).unwrap_or_else(|error| {
        panic!(
            "could not read {}: {error}. Copy {} and edit it for this computer.",
            source.display(),
            example.display()
        )
    });
    let settings: serde_json::Value = serde_json::from_str(&strip_comments(&text))
        .unwrap_or_else(|error| panic!("{} is not valid JSON: {error}", source.display()));

    let mut generated =
        String::from("// Generated by build.rs from the settings JSON. Do not edit.\n");
    for key in STRINGS {
        let value = settings.get(key).and_then(serde_json::Value::as_str).unwrap_or_else(|| {
            panic!(
                "{} is missing the setting \"{}\"; copy it from {}",
                source.display(),
                key,
                example.display()
            )
        });
        // Not every setting is read by every feature; one the current build never touches is
        // still configuration its owner may need, not dead code to delete.
        generated.push_str(&format!(
            "#[allow(dead_code)]\npub const {}: &str = {};\n",
            key.to_uppercase(),
            quote(value)
        ));
    }
    generated.push_str(&courses(&settings, source));

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("machine_settings.rs");
    std::fs::write(&out, generated)
        .unwrap_or_else(|error| panic!("could not write {}: {error}", out.display()));
}

/// The subjects this person studies, in the order they should appear.
fn courses(settings: &serde_json::Value, source: &Path) -> String {
    let listed = settings
        .get("courses")
        .and_then(serde_json::Value::as_array)
        .unwrap_or_else(|| {
            panic!(
                "{} has no \"courses\" array; the app needs at least one subject to watch",
                source.display()
            )
        });
    if listed.is_empty() {
        panic!(
            "{} lists no courses; add at least one subject folder",
            source.display()
        );
    }
    let mut out = String::from("pub const COURSES: &[CourseSpec] = &[\n");
    for (index, course) in listed.iter().enumerate() {
        let text = |key: &str, required: bool| -> String {
            match course.get(key).and_then(serde_json::Value::as_str) {
                Some(value) => value.to_string(),
                None if required => panic!(
                    "{}: course {} is missing \"{}\"",
                    source.display(),
                    index + 1,
                    key
                ),
                None => String::new(),
            }
        };
        let id = text("id", true);
        let label = text("label", true);
        let folder = text("folder", true);
        let mode = match course.get("mode").and_then(serde_json::Value::as_str) {
            Some(value) => value.to_string(),
            None => "lecture-deck".to_string(),
        };
        let kind = match course.get("kind").and_then(serde_json::Value::as_str) {
            Some(value) => value.to_string(),
            None => "lecture".to_string(),
        };
        let description = match course.get("description").and_then(serde_json::Value::as_str) {
            Some(value) => value.to_string(),
            None => format!("One guide per source in {label}."),
        };
        let lecture_files = match course.get("lecture_files").and_then(serde_json::Value::as_str) {
            Some(pattern) if !pattern.trim().is_empty() => format!("Some({})", quote(pattern)),
            _ => "None".to_string(),
        };
        out.push_str(&format!(
            "    CourseSpec {{ id: {}, label: {}, folder: {}, mode: {}, kind: {}, \
             description: {}, lecture_files: {}, order: {} }},\n",
            quote(&id),
            quote(&label),
            quote(&folder),
            quote(&mode),
            quote(&kind),
            quote(&description),
            lecture_files,
            index
        ));
    }
    out.push_str("];\n");
    out
}

/// The settings file is allowed `//` comments so it can explain itself; JSON is not.
fn strip_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        let mut in_string = false;
        let mut escaped = false;
        let mut cut = line.len();
        let bytes: Vec<char> = line.chars().collect();
        for (index, character) in bytes.iter().enumerate() {
            if in_string {
                if escaped {
                    escaped = false;
                } else if *character == '\\' {
                    escaped = true;
                } else if *character == '"' {
                    in_string = false;
                }
            } else if *character == '"' {
                in_string = true;
            } else if *character == '/' && bytes.get(index + 1) == Some(&'/') {
                cut = line
                    .char_indices()
                    .nth(index)
                    .map(|(byte, _)| byte)
                    .unwrap_or(line.len());
                break;
            }
        }
        out.push_str(&line[..cut]);
        out.push('\n');
    }
    out
}

/// A Rust string literal that a backslash or a quote in a path cannot break.
fn quote(value: &str) -> String {
    let mut literal = String::from("\"");
    for character in value.chars() {
        match character {
            '"' => literal.push_str("\\\""),
            '\\' => literal.push_str("\\\\"),
            _ => literal.push(character),
        }
    }
    literal.push('"');
    literal
}
