<script>
import { tick } from 'svelte';
import { jobs,recentJobs,selectedJobId } from '../stores/jobs.js';
import { currentView,historyReturnView,actionNotice } from '../stores/navigation.js';
import { historyLoading,historyError,historyMutation,refreshHistory,manageHistory } from '../stores/history.js';
import { statusLabel,dateTime,isActive } from './ui.js';
let {full=false}=$props();
let query=$state('');let filter=$state('all');let visibility=$state('all');let limit=$state(50);let error=$state('');
let deleting=$state(null);let dialog=$state(null);let cancelButton=$state(null);let heading=$state(null);let returnFocus;
const candidates=$derived(full?$jobs:$recentJobs);
const filtered=$derived(candidates.filter(j=>{const text=[j.filename,j.filepath,j.folder,j.summary].join(' ').toLowerCase();const match=filter==='all'||(filter==='active'?isActive(j.status):filter==='resumable'?j.canResume:filter==='attention'?['failed','interrupted','blocked','cancelled'].includes(j.status):j.status===filter);const visible=!full||visibility==='all'||(visibility==='archived'?!!j.archivedAt:!j.archivedAt);return visible&&match&&text.includes(query.trim().toLowerCase());}));
const canClear=$derived($recentJobs.some(j=>!isActive(j.status)));
$effect(()=>{query;filter;visibility;limit=50;});
$effect(()=>{if(deleting&&dialog&&!dialog.open){dialog.showModal();cancelButton?.focus();}});
function open(job){$historyReturnView=full?'full-history':'history';$selectedJobId=job.id;$currentView='run';}
async function change(action,id){error='';try{await manageHistory(action,id);$actionNotice=action==='clear'?'Recents cleared. Records are kept in Settings → Full history.':action==='archive'?'Removed from Recents. The record is kept in Full history.':'Restored to Recents.';}catch(e){error=String(e);}}
function askDelete(job,event){error='';returnFocus=event.currentTarget;deleting=job;}
async function closeDelete(){if($historyMutation)return;dialog?.close();deleting=null;error='';await tick();returnFocus?.isConnected&&returnFocus.focus();}
async function confirmDelete(){if($historyMutation||!deleting)return;error='';try{await manageHistory('delete',deleting.id);dialog?.close();deleting=null;$actionNotice='History record permanently deleted. Source files and saved guides were kept.';await tick();heading?.focus();}catch(e){error=String(e);}}
</script>
<section class="page" aria-labelledby="history-title"><div class="page-inner">
{#if full}<button class="button ghost back-settings" onclick={()=>{$currentView='settings';}}>← Settings</button>{/if}
<div class="page-heading"><div><h1 id="history-title" bind:this={heading} tabindex="-1">{full?'Full history':'History'}</h1><p>{full?'All saved attempts, including records removed from Recents.':'Recent attempts, their outcomes, and what you can do next.'}</p></div><div class="heading-actions"><button class="button secondary" disabled={$historyLoading||!!$historyMutation} onclick={refreshHistory}>{$historyLoading?'Refreshing…':'Refresh'}</button>{#if !full}<button class="button secondary" disabled={!canClear||!!$historyMutation} onclick={()=>change('clear')}>Clear recents</button>{/if}</div></div>
{#if !full}<p class="archive-help">Clearing Recents keeps records in <button class="text-link" onclick={()=>{$currentView='full-history';}}>Settings → Full history</button>. Active guides stay visible.</p>{/if}
<div class="filters"><label class="search"><span class="sr-only">Search history</span><input type="search" placeholder="Search guides, courses, or paths" bind:value={query}/></label><label><span class="sr-only">Filter by outcome</span><select aria-label="Filter history by outcome" bind:value={filter}><option value="all">All outcomes</option><option value="active">In progress</option><option value="done">Succeeded</option><option value="attention">Needs attention</option><option value="failed">Failed</option><option value="interrupted">Interrupted</option><option value="cancelled">Cancelled</option><option value="blocked">Blocked</option><option value="resumable">Can resume</option></select></label>{#if full}<label><span class="sr-only">Record visibility</span><select aria-label="Record visibility" bind:value={visibility}><option value="all">All records</option><option value="archived">Archived</option><option value="recent">In Recents</option></select></label>{/if}</div>
{#if $historyError}<div class="error-box" role="alert"><strong>History could not be loaded.</strong><p>Your visible runs have been kept. Refresh to try again.</p><details><summary>Technical details</summary><pre>{$historyError}</pre></details></div>{/if}
{#if error&&!deleting}<p class="error-box" role="alert">{error}</p>{/if}
<div class="result-count" role="status">{filtered.length} {filtered.length===1?'attempt':'attempts'}{query||filter!=='all'||visibility!=='all'?' matching your filters':''}</div>
<div class="history-list">{#each filtered.slice(0,limit) as job (job.id)}<article class="history-entry"><button class="history-row" onclick={()=>open(job)}><div class="row-main"><div class="row-title"><strong>{job.filename}</strong>{#if job.canResume}<span class="resume-label">Can resume</span>{/if}{#if job.archivedAt}<span class="archive-label">Archived</span>{/if}</div><p class="summary">{job.summary||job.activity||statusLabel(job.status)}</p><small>{job.folder||'Course guide'} · {dateTime(job.startedAt)}</small></div><div class="row-outcome"><span class="status-badge {job.status}">{statusLabel(job.status)}</span><span class="view">View details →</span></div></button>
{#if !isActive(job.status)}<div class="record-actions">{#if job.archivedAt}<button class="button ghost" disabled={!!$historyMutation} onclick={()=>change('restore',job.id)} aria-label={'Restore '+job.filename+' to Recents'}>Restore to Recents</button>{#if full}<button class="button ghost delete-record" disabled={!!$historyMutation} onclick={event=>askDelete(job,event)} aria-label={'Permanently delete history for '+job.filename}>Delete permanently…</button>{/if}{:else}<button class="button ghost" disabled={!!$historyMutation} onclick={()=>change('archive',job.id)} aria-label={'Remove '+job.filename+' from Recents'}>Remove from Recents</button>{/if}</div>{/if}</article>
{:else}<div class="empty"><h2>{$historyError&&!candidates.length?'History is unavailable':$historyLoading&&!candidates.length?'Loading history…':query||filter!=='all'||visibility!=='all'?'No matching attempts':full?'No recorded attempts yet':'No recent attempts'}</h2><p>{$historyError&&!candidates.length?'Refresh to try loading your saved records again.':$historyLoading&&!candidates.length?'Reading saved attempts from this computer.':query||filter!=='all'||visibility!=='all'?'Try another search or outcome filter.':full?'New attempts will be recorded here.':'Cleared attempts are available in Settings → Full history. New attempts will appear here.'}</p>{#if query||filter!=='all'||visibility!=='all'}<button class="button secondary" onclick={()=>{query='';filter='all';visibility='all';}}>Clear filters</button>{/if}</div>{/each}</div>
{#if filtered.length>limit}<button class="button secondary more" onclick={()=>limit+=50}>Show more ({filtered.length-limit} remaining)</button>{/if}
<p class="history-note">Records are stored locally. Older saved artifacts may provide recovery evidence, but missing activity logs cannot be reconstructed.</p>
</div></section>
{#if deleting}<dialog bind:this={dialog} class="delete-dialog" aria-labelledby="delete-title" aria-describedby="delete-description" oncancel={event=>{event.preventDefault();closeDelete();}}><h2 id="delete-title">Permanently delete this history record?</h2><p class="delete-name">{deleting.filename}</p><p id="delete-description">Its saved activity and outcome will be removed from history and cannot be restored here. Source files, saved context, and generated guides will stay on disk.</p>{#if error}<p class="error-box" role="alert">{error}</p>{/if}<div class="dialog-actions"><button class="button secondary" bind:this={cancelButton} disabled={!!$historyMutation} onclick={closeDelete}>Cancel</button><button class="button danger" disabled={!!$historyMutation} onclick={confirmDelete}>{$historyMutation==='delete'?'Deleting…':'Delete permanently'}</button></div></dialog>{/if}
<style>

.filters{display:flex;flex-wrap:wrap;gap:.75rem;margin-bottom:1rem;}.search{flex:1 1 12rem;min-width:0;}.search input{width:100%;}.filters select{width:100%;}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0);}.result-count{font-size:.85rem;color:var(--text-secondary);margin:1rem 0 .5rem;}.history-entry{border-bottom:1px solid var(--border-panel);}.history-row{display:flex;justify-content:space-between;gap:1rem;width:100%;text-align:left;padding:1.2rem .5rem;}.history-row:hover{background:var(--bg-surface);}.row-main{min-width:0;flex:1;}.row-title{display:flex;gap:.5rem;flex-wrap:wrap;align-items:baseline;}.row-title strong{font-weight:600;overflow-wrap:anywhere;}.summary{margin:.35rem 0;color:var(--text-secondary);font-size:.95rem;overflow-wrap:anywhere;}.row-main small{color:var(--text-tertiary);overflow-wrap:anywhere;}.row-outcome{display:flex;flex-direction:column;align-items:flex-end;gap:.7rem;}.view{font-size:.85rem;color:var(--text-secondary);}.resume-label{font-size:.8rem;color:var(--accent-green);}.empty{padding:3rem 0;display:grid;gap:1rem;justify-items:start;}.empty p{color:var(--text-secondary);}.history-note{margin-top:1.5rem;color:var(--text-tertiary);font-size:.85rem;max-width:70ch;}.more{margin-top:1rem;}@container(max-width:600px){.history-row{flex-direction:column;}.row-outcome{flex-direction:row;justify-content:space-between;align-items:center;}.filters>label{width:100%;}}

.heading-actions,.record-actions{display:flex;flex-wrap:wrap;gap:.5rem;}.record-actions{padding:0 .5rem .75rem;}.record-actions .button{font-size:.85rem;}.delete-record{color:var(--accent-red);}.archive-label{font-size:.8rem;color:var(--text-tertiary);}.archive-help{margin:-.4rem 0 1.2rem;color:var(--text-secondary);font-size:.9rem;}.text-link{text-decoration:underline;text-underline-offset:3px;color:var(--accent-blue);}.back-settings{margin-bottom:.75rem;}.delete-dialog{margin:auto;padding:1.5rem;width:min(32rem,calc(100% - 2rem));max-height:calc(100% - 2rem);overflow:auto;border:1px solid var(--border-subtle);border-radius:10px;background:var(--bg-panel);color:var(--text-primary);box-shadow:0 12px 48px #0006;}.delete-dialog::backdrop{background:#0009;}.delete-dialog p{margin-top:1rem;overflow-wrap:anywhere;}.delete-name{font-weight:600;}.dialog-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:.75rem;margin-top:1.5rem;}.button.danger{background:var(--accent-red);color:var(--bg-base);}h1:focus{outline:none;}
</style>