export function desktopFixture() {
  const callbacks=new Map();const listeners=new Map();let next=0;
  const sources=['C:/Courses/Networks/CH01_Introduction.pdf','C:/Courses/Algorithms/Lecture 02 - Sorting.pdf','C:/Courses/Operating Systems/Lecture 03 - Processes with a deliberately very long source filename.pdf','C:/Courses/Writing/Week 2.pptx'];
  const records=['done','failed','interrupted','blocked','cancelled','working'].map((status,i)=>({jobId:'fixture-'+i,sourcePath:sources[i%4],status,startedAt:Date.now()-(i+1)*3600000,finishedAt:status==='working'?null:Date.now()-i*3600000,summary:status==='done'?'The guide passed validation and was saved.':status==='failed'?'The writing provider was unavailable. Saved context is ready to resume.':'This is a recorded '+status+' attempt.',canResume:status==='failed',canRetry:status==='interrupted',canOpenOutput:status==='done',events:[{timestamp:Date.now()-600000,level:'info',message:'The source files were checked.'},{timestamp:Date.now(),level:status==='failed'?'error':'info',message:status==='failed'?'The provider reached its usage limit.':'Context collection finished.'}]}));
  const saved=localStorage.getItem('fixture-history');if(saved){records.splice(0,records.length,...JSON.parse(saved));}
  const config={providers:[{id:'codex-chatgpt',label:'Codex',models:['gpt-5.6-sol','gpt-5.6-terra','gpt-5.6-luna'],efforts:['low','medium','high','xhigh','max'],default_model:'gpt-5.6-luna',default_effort:'medium'},{id:'claude-code',label:'Claude',models:['claude-opus-4-8','claude-opus-5','fable','opus','sonnet','haiku'],efforts:['low','medium','high','xhigh','max'],default_model:'claude-opus-4-8',default_effort:'high'}],default_prep:{provider:'codex-chatgpt',model:'gpt-5.6-luna',effort:'medium'},collection_fallback_chain:[{provider:'codex-chatgpt',model:'gpt-5.6-terra',effort:'medium'},{provider:'codex-chatgpt',model:'gpt-5.6-sol',effort:'medium'}],default_writer:{provider:'claude-code',model:'claude-opus-4-8',effort:'high'},fallback_chain:[{provider:'codex-chatgpt',model:'gpt-5.6-sol',effort:'medium'}],course_profiles:[{id:'networks',label:'Computer Networks',description:'Lecture guides with cumulative explanations.'},{id:'algorithms',label:'Computer Algorithms'},{id:'os',label:'Operating Systems'},{id:'circuit',label:'Circuit Theory & Measurement Lab'},{id:'writing',label:'Scientific Writing'}],default_course_profile:'auto',require_slide_coverage:true,require_visuals:true};
  const authStatuses=[{provider:'codex-chatgpt',label:'OpenAI Codex',installed:true,authenticated:true,accountLabel:'ChatGPT account',authMethod:'ChatGPT',detail:'Ready for Guide Watcher generation.'},{provider:'claude-code',label:'Claude Code',installed:true,authenticated:true,accountLabel:'student@example.com',authMethod:'Claude Max',detail:'Ready for Guide Watcher generation.'}];
  window.fixture={sources,records,config,authStatuses,calls:[],error:null,delay:0};
  window.emitFixture=(event,payload)=>{for(const id of listeners.get(event)||[])callbacks.get(id)?.({event,payload});};
  window.__TAURI_EVENT_PLUGIN_INTERNALS__={unregisterListener(){}};
  window.__TAURI_INTERNALS__={transformCallback(fn){callbacks.set(++next,fn);return next;},async invoke(command,args){window.fixture.calls.push({command,args});if(command==='plugin:event|listen'){listeners.set(args.event,[...(listeners.get(args.event)||[]),args.handler]);return args.handler;}if(command==='plugin:event|unlisten'||command==='plugin:clipboard-manager|write_text')return;if(window.fixture.delay)await new Promise(r=>setTimeout(r,window.fixture.delay));if(window.fixture.error)throw new Error(window.fixture.error);if(command==='get_config')return config;if(command==='get_provider_auth_statuses')return authStatuses;if(command==='start_provider_login')return {provider:args.provider,sessionId:'auth-fixture',state:'starting'};if(command==='cancel_provider_login')return;if(command==='scan_watch_folder'||command==='pick_files')return sources;if(command==='pick_prep_file')return null;if(command==='approve_files')return args.filePaths.map((path,i)=>({jobId:'new-'+i,primarySource:path,outputPath:path.replace(/\.pdf$/i,'_Guide.md'),courseProfile:'auto'}));if(command==='list_job_history')return records;if(['archive_history_job','clear_recent_history','restore_history_job','delete_history_job'].includes(command)){
    const active=r=>['starting','working','queued'].includes(r.status);
    if(command==='clear_recent_history'){for(const r of records)if(!active(r)&&!r.archivedAt)r.archivedAt=Date.now();}
    else {const r=records.find(r=>r.jobId===args.jobId);if(!r)throw new Error('History record not found.');if(active(r))throw new Error('Active jobs cannot be changed.');if(command==='archive_history_job')r.archivedAt=Date.now();if(command==='restore_history_job')r.archivedAt=null;if(command==='delete_history_job'){if(!r.archivedAt)throw new Error('Archive this record first.');records.splice(records.indexOf(r),1);}}
    if(window.fixture.persistHistory)localStorage.setItem('fixture-history',JSON.stringify(records));return;
  }if(command.endsWith('_history_job'))return {jobId:'retry-fixture'};if(command==='open_history_output')return;throw new Error('Unexpected fixture command: '+command);}};
}
