// src-tauri/src/config.rs
use serde::Serialize;

// This computer's folders and tool paths. Generated by build.rs from
// guide-watcher.local.json (yours, git-ignored) or guide-watcher.example.json (the template),
// so the source can be shared without carrying anyone's directory layout.
include!(concat!(env!("OUT_DIR"), "/machine_settings.rs"));
pub const DGIST_LMS_AGENT_ROOT: &str = LMS_AGENT_ROOT;
pub const DGIST_LMS_NODE_EXECUTABLE: &str = LMS_NODE_EXECUTABLE;
pub const DGIST_LMS_TSX_CLI: &str = LMS_TSX_CLI;
pub const DGIST_FFMPEG_EXECUTABLE: &str = FFMPEG_EXECUTABLE;
pub const DGIST_FFPROBE_EXECUTABLE: &str = FFPROBE_EXECUTABLE;

pub const VERIFY_REPAIR_ATTEMPTS: u32 = 3;
/// Bounded strictly-additive deepening passes run before verification.
/// Deepening passes that add worked examples and traces while the guide is under the
/// depth target. Each pass is strictly additive and structurally validated.
pub const GUIDE_DEPTH_PASSES: u32 = 2;
/// Pedagogy passes that run after the depth passes. Each one asks the verifier for its
/// advisory (missing examples, terms used before definition, unwoven figures, thin
/// sections) and fixes exactly those items.
pub const GUIDE_PEDAGOGY_PASSES: u32 = 1;
/// How many times the writer harness may run `./verify_draft.sh` and fix what it reports
/// within one session before it must stop and report what remains.
pub const HARNESS_VERIFY_ROUNDS: u32 = 4;
/// A draft left by a failed attempt is continued (not rewritten) when it has at least this
/// many words and a table of contents.
pub const CONTINUE_DRAFT_MIN_WORDS: usize = 1_500;
/// Words per rendered slide the enrichment loop aims for. The lint floor is a
/// shallow-output backstop (240); this is the quality target that stops the loop
/// early once a guide is genuinely deep enough.
pub const DEPTH_TARGET_WORDS_PER_SLIDE: usize = 450;

pub const DGIST_LMS_EXPECTED_PACKAGE_MANAGER: &str = "pnpm@10.8.1";

pub const TRANSCRIPTION_REQUIREMENT: &str = "faster-whisper==1.2.1";
pub const TRANSCRIPTION_MODEL: &str = "mobiuslabsgmbh/faster-whisper-large-v3-turbo";

pub const CIRCUIT_LAB_FRAME_COUNT: u8 = 40;

pub const WATCHED_EXTENSIONS: &[&str] = &[".pdf", ".html", ".pptx", ".docx"];
pub const SKIP_FOLDERS: &[&str] = &[
    "_automation",
    "__MACOSX",
    ".ipynb_checkpoints",
    ".git",
    "node_modules",
    ".DS_Store",
    ".claude",
    ".vscode",
    ".codex_tmp",
    "Archive-ugrp",
    "kisub kim",
    "output",
    "datalab",
];
pub const SKIP_PATTERNS: &[&str] = &[
    "libgen.li",
    "syllabus",
    "guideline",
    ".prep.md",
    "introduction to ni elvis",
];

pub const BATCH_WINDOW_SECS: u64 = 3;
pub const COOLDOWN_SECS: u64 = 60;
pub const FILE_STABILITY_TIMEOUT_SECS: u64 = 20;
pub const FILE_STABILITY_POLL_MS: u64 = 1000;
pub const DIR_SCAN_DELAY_MS: u64 = 1500;

pub const DEFAULT_PROVIDER: &str = "codex-chatgpt";
pub const DEFAULT_MODEL: &str = "gpt-5.6-luna";
pub const DEFAULT_EFFORT: &str = "medium";
pub const CODEX_MODELS: &[&str] = &["gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna"];
pub const CODEX_EFFORTS: &[&str] = &["low", "medium", "high", "xhigh", "max"];

pub const CLAUDE_MODELS: &[&str] = &[
    "claude-opus-4-8",
    "claude-opus-5",
    "fable",
    "opus",
    "sonnet",
    "haiku",
];
pub const CLAUDE_EFFORTS: &[&str] = &["low", "medium", "high", "xhigh", "max"];

// Economical collection path: Luna handles normal units, Terra retries failed units,
// and Sol is reserved for material the less expensive models could not validate.
pub const CODEX_PREP_PHASE_MODEL: &str = "gpt-5.6-luna";
pub const CODEX_PREP_PHASE_EFFORT: &str = "medium";
pub const CODEX_COLLECTION_FALLBACKS: &[(&str, &str)] =
    &[("gpt-5.6-terra", "medium"), ("gpt-5.6-sol", "medium")];

pub const DEFAULT_WRITER_PROVIDER: &str = "claude-code";
pub const DEFAULT_WRITER_MODEL: &str = "claude-opus-4-8";
pub const DEFAULT_WRITER_EFFORT: &str = "high";
pub const CLAUDE_FALLBACK_MODEL: &str = "";
pub const CLAUDE_FALLBACK_EFFORT: &str = "";
pub const CODEX_FINAL_FALLBACK_MODEL: &str = "gpt-5.6-sol";
pub const CODEX_FINAL_FALLBACK_EFFORT: &str = "medium";
pub const DEFAULT_COURSE_PROFILE: &str = "auto";

#[derive(Serialize, Clone, Debug, PartialEq, Eq)]
pub struct PhasePreset {
    pub provider: String,
    pub model: String,
    pub effort: String,
}

impl PhasePreset {
    fn new(provider: &str, model: &str, effort: &str) -> Self {
        Self {
            provider: provider.to_string(),
            model: model.to_string(),
            effort: effort.to_string(),
        }
    }
}

#[derive(Serialize, Clone, Debug, PartialEq, Eq)]
pub struct CourseProfile {
    pub id: String,
    pub label: String,
    pub root: String,
    pub guide_mode: String,
    pub description: String,
    pub require_slide_coverage: bool,
    pub require_visuals: bool,
    pub cumulative: bool,
}

impl CourseProfile {
    fn new(id: &str, label: &str, root: &str, guide_mode: &str, description: &str) -> Self {
        Self {
            id: id.to_string(),
            label: label.to_string(),
            root: root.to_string(),
            guide_mode: guide_mode.to_string(),
            description: description.to_string(),
            require_slide_coverage: true,
            require_visuals: true,
            cumulative: true,
        }
    }
}

// Appended to every successfully completed guide so we can detect incomplete runs
#[derive(Serialize, Clone)]
pub struct ProviderOption {
    pub id: String,
    pub label: String,
    pub models: Vec<String>,
    pub default_model: String,
    pub efforts: Vec<String>,
    pub default_effort: String,
    pub help: String,
}

#[derive(Serialize, Clone)]
pub struct ConfigResponse {
    pub providers: Vec<ProviderOption>,
    pub default_prep: PhasePreset,
    pub collection_fallback_chain: Vec<PhasePreset>,
    pub default_writer: PhasePreset,
    pub fallback_chain: Vec<PhasePreset>,
    pub course_profiles: Vec<CourseProfile>,
    pub default_course_profile: String,
    pub require_slide_coverage: bool,
    pub require_visuals: bool,
}

impl ConfigResponse {
    pub fn new() -> Self {
        Self {
            providers: vec![
                ProviderOption {
                    id: "codex-chatgpt".to_string(),
                    label: "OpenAI Codex (ChatGPT login)".to_string(),
                    models: CODEX_MODELS.iter().map(|s| s.to_string()).collect(),
                    default_model: DEFAULT_MODEL.to_string(),
                    efforts: CODEX_EFFORTS.iter().map(|s| s.to_string()).collect(),
                    default_effort: DEFAULT_EFFORT.to_string(),
                    help: "Uses Codex CLI logged in with ChatGPT. No OpenAI API key required."
                        .to_string(),
                },
                ProviderOption {
                    id: "claude-code".to_string(),
                    label: "Claude Code (subscription login)".to_string(),
                    models: CLAUDE_MODELS.iter().map(|s| s.to_string()).collect(),
                    default_model: DEFAULT_WRITER_MODEL.to_string(),
                    efforts: CLAUDE_EFFORTS.iter().map(|s| s.to_string()).collect(),
                    default_effort: DEFAULT_WRITER_EFFORT.to_string(),
                    help: "Uses your existing Claude Code login. The selected model and effort are passed directly to Claude Code. Process only trusted course files."
                        .to_string(),
                },
            ],
            default_prep: PhasePreset::new(
                DEFAULT_PROVIDER,
                CODEX_PREP_PHASE_MODEL,
                CODEX_PREP_PHASE_EFFORT,
            ),
            collection_fallback_chain: CODEX_COLLECTION_FALLBACKS
                .iter()
                .map(|(model, effort)| PhasePreset::new(DEFAULT_PROVIDER, model, effort))
                .collect(),
            default_writer: PhasePreset::new(
                DEFAULT_WRITER_PROVIDER,
                DEFAULT_WRITER_MODEL,
                DEFAULT_WRITER_EFFORT,
            ),
            fallback_chain: vec![PhasePreset::new(
                DEFAULT_PROVIDER,
                CODEX_FINAL_FALLBACK_MODEL,
                CODEX_FINAL_FALLBACK_EFFORT,
            )],
            course_profiles: vec![
                CourseProfile::new(
                    "computer-networks",
                    "Computer Networks",
                    &format!("{FIFTH_SEMESTER_ROOT}/Computer Networks"),
                    "lecture-deck",
                    "One cumulative teaching guide per lecture deck, covering every slide.",
                ),
                CourseProfile::new(
                    "computer-algorithms",
                    "Computer Algorithms",
                    &format!("{FIFTH_SEMESTER_ROOT}/Computer Algorithms"),
                    "lecture-deck",
                    "One cumulative teaching guide per lecture deck, with worked derivations and verification.",
                ),
                CourseProfile::new(
                    "operating-systems",
                    "Operating Systems",
                    &format!("{FIFTH_SEMESTER_ROOT}/Operating Systems"),
                    "lecture-deck",
                    "One cumulative teaching guide per lecture deck, covering every slide and mechanism.",
                ),
                CourseProfile::new(
                    "circuit-lab",
                    "Circuit Theory & Measurement Lab",
                    &format!("{FIFTH_SEMESTER_ROOT}/Circuit Theory & Measurement Lab"),
                    "weekly-lab",
                    "One visual, step-by-step guide per Friday lab, grounded in the LMS announcement and video.",
                ),
                CourseProfile::new(
                    "scientific-writing",
                    "Scientific Writing",
                    &format!("{FIFTH_SEMESTER_ROOT}/Scientific Writing"),
                    "weekly-material",
                    "One cumulative guide per teaching week, preserving the existing Week 1 guide.",
                ),
                CourseProfile::new(
                    "legacy-fourth-semester",
                    "4th Semester (legacy)",
                    FOURTH_SEMESTER_ROOT,
                    "legacy-auto",
                    "Retains the existing fourth-semester workflow for manual scans and older guides.",
                ),
            ],
            default_course_profile: DEFAULT_COURSE_PROFILE.to_string(),
            require_slide_coverage: true,
            require_visuals: true,
        }
    }
}

/// Check if a file path should be skipped based on folder names and filename patterns.
pub fn should_skip(filepath: &str) -> bool {
    let normalized = filepath.replace('\\', "/");
    let parts: Vec<&str> = normalized.split('/').collect();

    // Check skip folders (any path component)
    for part in &parts {
        let lower = part.to_lowercase();
        if [
            ".gwverify",
            ".gwwork",
            ".gwtxn",
            ".gwfailed",
            ".gwdelete",
            "_assets",
        ]
        .iter()
        .any(|suffix| lower.ends_with(suffix))
            || SKIP_FOLDERS.iter().any(|f| f.eq_ignore_ascii_case(part))
        {
            return true;
        }
    }

    // Check skip patterns (filename substring, case-insensitive)
    if let Some(filename) = parts.last() {
        let lower = filename.to_lowercase();
        if SKIP_PATTERNS.iter().any(|pattern| {
            if pattern.starts_with('.') {
                lower.ends_with(pattern)
            } else {
                lower.contains(pattern)
            }
        }) {
            return true;
        }
    }

    false // not skipped
}

/// Check if file extension is watched.
pub fn is_watched_extension(filepath: &str) -> bool {
    let lower = filepath.to_lowercase();
    WATCHED_EXTENSIONS.iter().any(|ext| lower.ends_with(ext))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn provider<'a>(config: &'a ConfigResponse, id: &str) -> &'a ProviderOption {
        config
            .providers
            .iter()
            .find(|provider| provider.id == id)
            .unwrap_or_else(|| panic!("missing provider {id}"))
    }

    #[test]
    fn cross_provider_pipeline_defaults_are_explicit_and_supported() {
        let config = ConfigResponse::new();
        let codex = provider(&config, "codex-chatgpt");

        assert_eq!(DEFAULT_PROVIDER, "codex-chatgpt");
        assert_eq!(DEFAULT_MODEL, "gpt-5.6-luna");
        assert_eq!(DEFAULT_EFFORT, "medium");
        assert_eq!(CODEX_PREP_PHASE_MODEL, "gpt-5.6-luna");
        assert_eq!(CODEX_PREP_PHASE_EFFORT, "medium");
        assert_eq!(codex.default_model, DEFAULT_MODEL);
        assert_eq!(codex.default_effort, DEFAULT_EFFORT);
        assert_eq!(codex.label, "OpenAI Codex (ChatGPT login)");

        assert_eq!(
            config.default_prep,
            PhasePreset::new("codex-chatgpt", "gpt-5.6-luna", "medium")
        );
        assert_eq!(
            config.collection_fallback_chain,
            [
                PhasePreset::new("codex-chatgpt", "gpt-5.6-terra", "medium"),
                PhasePreset::new("codex-chatgpt", "gpt-5.6-sol", "medium"),
            ]
        );
        assert_eq!(
            config.default_writer,
            PhasePreset::new("claude-code", "claude-opus-4-8", "high")
        );
        assert_eq!(
            config.fallback_chain,
            [PhasePreset::new("codex-chatgpt", "gpt-5.6-sol", "medium")]
        );
        let claude = provider(&config, "claude-code");
        assert_eq!(claude.label, "Claude Code (subscription login)");
        assert_eq!(
            claude.models,
            [
                "claude-opus-4-8",
                "claude-opus-5",
                "fable",
                "opus",
                "sonnet",
                "haiku"
            ]
        );
        assert_eq!(claude.default_model, "claude-opus-4-8");
        assert_eq!(claude.default_effort, "high");
    }

    #[test]
    fn codex_models_and_efforts_are_exposed_in_safe_order() {
        assert_eq!(
            CODEX_MODELS,
            ["gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna"]
        );
        assert_eq!(CODEX_EFFORTS, ["low", "medium", "high", "xhigh", "max"]);
        assert!(!CODEX_EFFORTS.contains(&"ultra"));

        let config = ConfigResponse::new();
        let codex = provider(&config, "codex-chatgpt");
        assert_eq!(codex.models, CODEX_MODELS);
        assert_eq!(codex.efforts, CODEX_EFFORTS);
    }

    #[test]
    fn config_exposes_only_the_fixed_cli_provider_chain() {
        let config = ConfigResponse::new();
        let provider_ids = config
            .providers
            .iter()
            .map(|provider| provider.id.as_str())
            .collect::<Vec<_>>();
        assert_eq!(provider_ids, ["codex-chatgpt", "claude-code"]);
        assert!(!config
            .providers
            .iter()
            .flat_map(|provider| provider.models.iter())
            .any(|model| model == "gpt-5.5"));

        let response = serde_json::to_value(config).expect("serialize config");
        for removed_field in [
            "default_base_url",
            "needs_api_key",
            "model_refresh",
            "default_prep_model",
            "default_prep_effort",
        ] {
            assert!(
                response["providers"]
                    .as_array()
                    .expect("provider array")
                    .iter()
                    .all(|provider| provider.get(removed_field).is_none()),
                "retired provider field leaked into config: {removed_field}"
            );
        }
    }

    #[test]
    fn fifth_semester_profiles_and_legacy_profile_are_exposed() {
        let config = ConfigResponse::new();
        let ids: Vec<&str> = config
            .course_profiles
            .iter()
            .map(|profile| profile.id.as_str())
            .collect();

        for expected in [
            "computer-networks",
            "computer-algorithms",
            "operating-systems",
            "circuit-lab",
            "scientific-writing",
            "legacy-fourth-semester",
        ] {
            assert!(ids.contains(&expected), "missing course profile {expected}");
        }
        assert!(config.course_profiles.iter().all(|profile| {
            profile.require_slide_coverage && profile.require_visuals && profile.cumulative
        }));
        assert_eq!(WATCH_DIR, FIFTH_SEMESTER_ROOT);
        assert!(WATCHED_EXTENSIONS.contains(&".pptx"));
        assert!(WATCHED_EXTENSIONS.contains(&".docx"));
    }

    #[test]
    fn should_skip_matches_folder_and_filename_boundaries_case_insensitively() {
        for path in [
            "course/node_modules/lecture.pdf",
            "course/NODE_MODULES/lecture.pdf",
            r"course\.git\lecture.pdf",
            "course/run.gwverify/slide.html",
            "course/RUN.GWVERIFY/slide.html",
            "course/run.gwwork/slide.html",
            "course/run.gwtxn/slide.html",
            "course/run.gwfailed/slide.html",
            "course/run.gwdelete/slide.html",
            "course/Guide_assets/slide.html",
            "course/syllabus-notes.pdf",
            "course/GUIDELINE.HTML",
            "course/unit.PREP.MD",
            "course/Introduction to NI ELVIS.pdf",
        ] {
            assert!(should_skip(path), "expected path to be skipped: {path}");
        }

        for path in [
            "",
            "course/node_modules_backup/lecture.pdf",
            "course/.gitignore/lecture.pdf",
            "course/run.gwverify.tmp/slide.html",
            "course/run.gwverify-backup/slide.html",
            "course/run.gwdelete.tmp/slide.html",
            "course/Guide_assets_backup/slide.html",
            "course/syllab.us-notes.pdf",
            "course/guide-line.html",
            "course/unit.prepmd.pdf",
            "course/unit.prep.md.pdf",
            "course/unit.prep.mdish.pdf",
        ] {
            assert!(
                !should_skip(path),
                "expected path to remain eligible: {path}"
            );
        }
    }

    #[test]
    fn watched_extensions_accept_case_variants_and_reject_malformed_near_matches() {
        for path in [
            "lecture.pdf",
            "lecture.PDF",
            "lesson.HtMl",
            "week-2.PPTX",
            "worksheet.DoCx",
            r"C:\course\deck.PdF",
        ] {
            assert!(
                is_watched_extension(path),
                "expected watched extension: {path}"
            );
        }

        for path in [
            "",
            "lecturepdf",
            "lecture.pdf.tmp",
            "lesson.htmlx",
            "deck.pptxm",
            "worksheet.docx.tmp",
            "lecture.pdf ",
            "course.pdf/notes.txt",
        ] {
            assert!(
                !is_watched_extension(path),
                "expected malformed or unsupported extension: {path}"
            );
        }
    }
}
